name: Blue-Green Deployment

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Ejecutar despliegue Blue-Green
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            source /etc/nginx/current_deploy.env

            if [ "$CURRENT_COLOR" = "blue" ]; then
              TARGET_COLOR="green"
              export APP_TARGET_IP="10.0.2.2"
              export APP_TARGET_PORT="8081"
            else
              TARGET_COLOR="blue"
              export APP_TARGET_IP="10.0.2.2"
              export APP_TARGET_PORT="8080"
            fi

            export DEPLOYMENT_COLOR=$TARGET_COLOR

            envsubst '${APP_TARGET_IP} ${APP_TARGET_PORT} ${DEPLOYMENT_COLOR}' \
              < /home/g2023171018/nginx-bluegreen/nginx.conf.template \
              > /etc/nginx/conf.d/default.conf

            sudo nginx -t && sudo systemctl reload nginx

            echo "CURRENT_COLOR=$TARGET_COLOR" | sudo tee /etc/nginx/current_deploy.env

            echo "✅ Despliegue completado: $TARGET_COLOR"
